services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.7.7
    ports:
      - "2181:2181"
    volumes:
      - zookeeper_data:/var/lib/zookeeper/data
      - zookeeper_logs:/var/lib/zookeeper/log
    environment:
      # - ZOOKEEPER_SERVER_ID=1 # required if using multiple zookeeper servers
      - ZOOKEEPER_CLIENT_PORT=2181  # required
      - ZOOKEEPER_TICK_TIME=2000  # optional configure time for heartbeats and timeouts => determine session timeouts = tick time * tick sync limit
      - ZOOKEEPER_SYNC_LIMIT=2    # tick numbers for follower to sync with leader 

  kafka:
    image: confluentinc/cp-kafka:7.7.7
    ports:
      - "9092:9092"
      - "29092:29092"
    volumes:
      - kafka_data:/var/lib/kafka/data
    environment:
      # - KAFKA_BROKER_ID=1 # required if using multiple servers
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: true # optional (should have) Disable auto topic creation
      # Listener security protocol map - BẮT BUỘC
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      # Inter-broker listener
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      # ⭐ QUAN TRỌNG: Set replication factor = 1 cho single broker
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_DEFAULT_REPLICATION_FACTOR: 1
      KAFKA_MIN_INSYNC_REPLICAS: 1
      # - KAFKA_LOG_DIRS=/bitnami/kafka/logs # optional configure log directory
    depends_on:
      - zookeeper

  mysql:
    image: mysql:9.6.0
    ports: 
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=techbank
      - MYSQL_USER=user 
      - MYSQL_PASSWORD=user
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - default

  mongo:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db
    networks:
      - default

volumes:
  zookeeper_data:
    driver: local
  zookeeper_logs:
    driver: local
  kafka_data:
    driver: local
  mongo_data:
    driver: local
  mysql_data:
    driver: local

networks:
  default:
    external:
      name: techbankNet